[package]
name = "rusty_distrochooser"
version = "3.0.0"
authors = [ "Christoph Müller <me@0fury.de>" ]

[dependencies.iron]
version = "*"

[dependencies]
router = "*"
hyper = "*"
mysql = "*"
params = "*"
time = "0.1.36"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"