[package]
name = "rusty_distrochooser"
version = "3.0.0"
authors = [ "Christoph Müller <me@0fury.de>" ]

[dependencies.iron]
version = "*"

[dependencies]
router = "*"
hyper = "*"
mysql = "*"
params = "*"
time = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
